In [3]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.40-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.1-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading sqlalchemy-2.0.40-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 6.3 MB/s eta 0:00:00
Downloading greenlet-3.2.1-cp313-cp313-win_amd64.whl (295 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.2.1 sqlalchemy-2.0.40
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [125]:
connection = create_engine(f'mysql://root:root@localhost:3308/classicmodels')

In [129]:

customers_df = pd.read_sql_query("select * from customers",connection)
employees_df = pd.read_sql_query("select * from employees",connection)
offices_df = pd.read_sql_query("select * from offices",connection)
orderdetails_df = pd.read_sql_query("select * from orderdetails",connection)
orders_df = pd.read_sql_query("select * from orders",connection)
payments_df = pd.read_sql_query("select * from payments",connection)
productlines_df = pd.read_sql_query("select * from productlines",connection)
products_df = pd.read_sql_query("select * from products",connection)
customers_df.to_csv('customers.csv',index=False)
employees_df.to_csv('employees.csv',index=False)
offices_df.to_csv('offices.csv',index=False)
orderdetails_df.to_csv('orderdetails.csv',index=False)
orders_df.to_csv('orders.csv',index=False)
payments_df.to_csv('payments.csv',index=False)
productlines_df.to_csv('productlines.csv',index=False)
products_df.to_csv('products.csv',index=False)

In [130]:
customers_df.dtypes

customerNumber              int64
customerName               object
contactLastName            object
contactFirstName           object
phone                      object
addressLine1               object
addressLine2               object
city                       object
state                      object
postalCode                 object
country                    object
salesRepEmployeeNumber    float64
creditLimit               float64
dtype: object

In [133]:
customers_df.postalCode.unique()

array(['44000', '83030', '3004', '4110', '97562', '01-012', '60528',
       '94217', '10022', '28034', 'S-958 22', '1734', '69004', '079903',
       '70267', '069045', 'N 5804', '97823', '1756', '59000', '75012',
       '51247', ' 530-0003', '21240', 'EC2 5NT', '2', '58339', 'WX1 6LT',
       'V3F 2K1', '90003', '038988', '67000', None, '08022', '92561',
       '01307', '8200', 'H1J 1C3', '28001', '91217', 'PO31 7PJ', '31000',
       '10100', '75508', '78000', '50739', 'T2F 8M4', '80805', '2060',
       '24100', '2067', '1700', '1203', 'N 0106', '1043 GR', '12209',
       '90110', 'B-1180', '24067', '50553', 'WX3 6FW', '94019', '4101',
       'FIN-02271', '14776', '71270', '28023', '91003', '13008', '51100',
       '0028', '44087', '51003', '62005', '1675', '3012', 'B-6000',
       '5020', '1227 MM', '42100', '106-0032', '75016', '70563', '80686',
       '04179', '97561', 'S-844 67', '8010', '52066', '3150', '68306',
       '196143', '47625', '41101', 'WA1 1DP'], dtype=object)

In [138]:
'a' != None

True

In [161]:
age =20
if age>5:
    ticket = 10
else:
    ticket = 5
print(ticket)

ticket = 100 if age>5 else 25
ticket

10

100

In [ ]:
e = ['1','2','3']
w=''
for i in e:
    w = w+i
w

'123'

In [163]:
set((x,"odd") if x%2==1 else (x,"Even") for x in range(1,6))

{(1, 'odd'), (2, 'Even'), (3, 'odd'), (4, 'Even'), (5, 'odd')}

In [169]:
'python is very python'.replace('p','j')

'jython is very jython'

In [170]:
data =  [ x.replace('-','')  if x != None else '0' for x in customers_df.postalCode   ]
data = [ x.replace(' ','')  if x != None else '0' for x in data   ]
data = [ list('0' if y in 'QWERTYUIOPASDFGHJKLZXCVBNM' else y for y in x)  if x != None  else 0 for x in data   ]

In [ ]:
for index,value in enumerate(data):
    final = ''
    for j in value:
        final+=j
    data[index] = int(final)

In [178]:
customers_df.postalCode = data

In [179]:
customers_df.dtypes

customerNumber              int64
customerName               object
contactLastName            object
contactFirstName           object
phone                      object
addressLine1               object
addressLine2               object
city                       object
state                      object
postalCode                  int64
country                    object
salesRepEmployeeNumber    float64
creditLimit               float64
dtype: object

In [127]:
orders_df.head()

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,None,363
1,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128
2,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,None,181
3,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,None,121
4,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,None,141

In [89]:
# sales_df = pd.concat([customers_df,orders_df,orderdetails_df,payments_df],axis=1,join='outer')
sales_df = pd.merge(customers_df,orders_df,on="customerNumber")
sales_df = pd.merge(sales_df,orderdetails_df,on="orderNumber")
# sales_df = pd.merge(sales_df,payments_df,on="customerNumber")
sales_df = pd.merge(sales_df,products_df,on="productCode")
sales_df = pd.merge(sales_df,productlines_df,on="productLine")

In [90]:
sales_df

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,...,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,textDescription,htmlDescription,image
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:18,Classic Metal Creations,Die-cast model of the silver 1965 Aston Martin...,9042,65.96,124.44,Attention car enthusiasts: Make your wildest c...,None,None
1,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:18,Red Start Diecast,Features include opening and closing doors. Co...,8164,56.76,132.00,Attention car enthusiasts: Make your wildest c...,None,None
2,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:18,Gearbox Collectibles,This model features working front and rear sus...,8990,62.16,141.28,Attention car enthusiasts: Make your wildest c...,None,None
3,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:24,Carousel DieCast Legends,This diecast model of the 1966 Shelby Cobra 42...,8197,29.18,50.31,Attention car enthusiasts: Make your wildest c...,None,None
4,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94,Our motorcycles are state of the art replicas ...,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:12,Unimax Art Galleries,"Official logos and insignias, saddle bags loca...",9997,66.27,150.62,Our motorcycles are state of the art replicas ...,None,None
2992,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:18,Welly Diecast Productions,Intricately detailed with chrome accents and t...,4357,24.23,60.57,Our motorcycles are state of the art replicas ...,None,None
2993,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:24,Autoart Studio Design,Detailed scale replica with working suspension...,7003,60.86,112.70,Our motorcycles are state of the art replicas ...,None,None
2994,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:24,Highway 66 Mini Classics,Detailed scale replica with working suspension...,15,37.32,76.17,Our motorcycles are state of the art replicas ...,None,None
2995,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:32,Exoto Designs,Features official die-struck logos and baked e...,178,66.92,99.89,Our motorcycles are state of the art replicas ...,None,None

In [91]:
sales_df.head()

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,...,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,textDescription,htmlDescription,image
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:18,Classic Metal Creations,Die-cast model of the silver 1965 Aston Martin...,9042,65.96,124.44,Attention car enthusiasts: Make your wildest c...,None,None
1,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:18,Red Start Diecast,Features include opening and closing doors. Co...,8164,56.76,132.00,Attention car enthusiasts: Make your wildest c...,None,None
2,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:18,Gearbox Collectibles,This model features working front and rear sus...,8990,62.16,141.28,Attention car enthusiasts: Make your wildest c...,None,None
3,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Classic Cars,1:24,Carousel DieCast Legends,This diecast model of the 1966 Shelby Cobra 42...,8197,29.18,50.31,Attention car enthusiasts: Make your wildest c...,None,None
4,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94,Our motorcycles are state of the art replicas ...,None,None

In [92]:
print(sales_df.shape)
print(sales_df.ndim)
print(sales_df.size)

(2996, 34)
2
101864

In [93]:
sales_df.tail()

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,...,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,textDescription,htmlDescription,image
2991,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:12,Unimax Art Galleries,"Official logos and insignias, saddle bags loca...",9997,66.27,150.62,Our motorcycles are state of the art replicas ...,None,None
2992,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:18,Welly Diecast Productions,Intricately detailed with chrome accents and t...,4357,24.23,60.57,Our motorcycles are state of the art replicas ...,None,None
2993,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:24,Autoart Studio Design,Detailed scale replica with working suspension...,7003,60.86,112.70,Our motorcycles are state of the art replicas ...,None,None
2994,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:24,Highway 66 Mini Classics,Detailed scale replica with working suspension...,15,37.32,76.17,Our motorcycles are state of the art replicas ...,None,None
2995,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,Motorcycles,1:32,Exoto Designs,Features official die-struck logos and baked e...,178,66.92,99.89,Our motorcycles are state of the art replicas ...,None,None

In [94]:
print(sales_df.customerNumber.count())
print(sales_df.image.count())

2996
0

In [95]:
for i in sales_df.columns:
    print(f"{i} :{sales_df[i].count()} ")

customerNumber :2996
customerName :2996
contactLastName :2996
contactFirstName :2996
phone :2996
addressLine1 :2996
addressLine2 :592
city :2996
state :1337
postalCode :2823
country :2996
salesRepEmployeeNumber :2996
creditLimit :2996
orderNumber :2996
orderDate :2996
requiredDate :2996
shippedDate :2855
status :2996
comments :758
productCode :2996
quantityOrdered :2996
priceEach :2996
orderLineNumber :2996
productName :2996
productLine :2996
productScale :2996
productVendor :2996
productDescription :2996
quantityInStock :2996
buyPrice :2996
MSRP :2996
textDescription :2996
htmlDescription :0
image :0

In [96]:
sales_df.drop(['htmlDescription','image'],axis=1,inplace=True)

In [97]:
sales_df.drop_duplicates()

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,...,orderLineNumber,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,textDescription
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,2,1965 Aston Martin DB5,Classic Cars,1:18,Classic Metal Creations,Die-cast model of the silver 1965 Aston Martin...,9042,65.96,124.44,Attention car enthusiasts: Make your wildest c...
1,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,3,1999 Indy 500 Monte Carlo SS,Classic Cars,1:18,Red Start Diecast,Features include opening and closing doors. Co...,8164,56.76,132.00,Attention car enthusiasts: Make your wildest c...
2,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,4,1948 Porsche Type 356 Roadster,Classic Cars,1:18,Gearbox Collectibles,This model features working front and rear sus...,8990,62.16,141.28,Attention car enthusiasts: Make your wildest c...
3,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1,1966 Shelby Cobra 427 S/C,Classic Cars,1:24,Carousel DieCast Legends,This diecast model of the 1966 Shelby Cobra 42...,8197,29.18,50.31,Attention car enthusiasts: Make your wildest c...
4,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94,Our motorcycles are state of the art replicas ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,5,2002 Suzuki XREO,Motorcycles,1:12,Unimax Art Galleries,"Official logos and insignias, saddle bags loca...",9997,66.27,150.62,Our motorcycles are state of the art replicas ...
2992,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,4,1936 Harley Davidson El Knucklehead,Motorcycles,1:18,Welly Diecast Productions,Intricately detailed with chrome accents and t...,4357,24.23,60.57,Our motorcycles are state of the art replicas ...
2993,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,3,1997 BMW R 1100 S,Motorcycles,1:24,Autoart Studio Design,Detailed scale replica with working suspension...,7003,60.86,112.70,Our motorcycles are state of the art replicas ...
2994,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,2,1960 BSA Gold Star DBD34,Motorcycles,1:24,Highway 66 Mini Classics,Detailed scale replica with working suspension...,15,37.32,76.17,Our motorcycles are state of the art replicas ...
2995,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,1,1997 BMW F650 ST,Motorcycles,1:32,Exoto Designs,Features official die-struck logos and baked e...,178,66.92,99.89,Our motorcycles are state of the art replicas ...

In [98]:
sales_df.columns

Index(['customerNumber', 'customerName', 'contactLastName', 'contactFirstName',
       'phone', 'addressLine1', 'addressLine2', 'city', 'state', 'postalCode',
       'country', 'salesRepEmployeeNumber', 'creditLimit', 'orderNumber',
       'orderDate', 'requiredDate', 'shippedDate', 'status', 'comments',
       'productCode', 'quantityOrdered', 'priceEach', 'orderLineNumber',
       'productName', 'productLine', 'productScale', 'productVendor',
       'productDescription', 'quantityInStock', 'buyPrice', 'MSRP',
       'textDescription'],
      dtype='object')

In [99]:
sales_df['total'] = sales_df.quantityOrdered*sales_df.priceEach

In [100]:
sales_df

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,...,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,textDescription,total
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1965 Aston Martin DB5,Classic Cars,1:18,Classic Metal Creations,Die-cast model of the silver 1965 Aston Martin...,9042,65.96,124.44,Attention car enthusiasts: Make your wildest c...,3138.46
1,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1999 Indy 500 Monte Carlo SS,Classic Cars,1:18,Red Start Diecast,Features include opening and closing doors. Co...,8164,56.76,132.00,Attention car enthusiasts: Make your wildest c...,5282.64
2,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1948 Porsche Type 356 Roadster,Classic Cars,1:18,Gearbox Collectibles,This model features working front and rear sus...,8990,62.16,141.28,Attention car enthusiasts: Make your wildest c...,3986.84
3,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1966 Shelby Cobra 427 S/C,Classic Cars,1:24,Carousel DieCast Legends,This diecast model of the 1966 Shelby Cobra 42...,8197,29.18,50.31,Attention car enthusiasts: Make your wildest c...,2163.50
4,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,...,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94,Our motorcycles are state of the art replicas ...,4128.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,2002 Suzuki XREO,Motorcycles,1:12,Unimax Art Galleries,"Official logos and insignias, saddle bags loca...",9997,66.27,150.62,Our motorcycles are state of the art replicas ...,3581.79
2992,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,1936 Harley Davidson El Knucklehead,Motorcycles,1:18,Welly Diecast Productions,Intricately detailed with chrome accents and t...,4357,24.23,60.57,Our motorcycles are state of the art replicas ...,1544.40
2993,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,1997 BMW R 1100 S,Motorcycles,1:24,Autoart Studio Design,Detailed scale replica with working suspension...,7003,60.86,112.70,Our motorcycles are state of the art replicas ...,5974.17
2994,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,1960 BSA Gold Star DBD34,Motorcycles,1:24,Highway 66 Mini Classics,Detailed scale replica with working suspension...,15,37.32,76.17,Our motorcycles are state of the art replicas ...,4373.78
2995,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,...,1997 BMW F650 ST,Motorcycles,1:32,Exoto Designs,Features official die-struck logos and baked e...,178,66.92,99.89,Our motorcycles are state of the art replicas ...,3132.48

In [115]:
total_sale_per_cuutomer = sales_df.groupby(by="customerName",)[['total']].aggregate(['sum'])
total_sale_per_cuutomer

                                 total
                                   sum
customerName
AV Stores, Co.               148410.09
Alpha Cognac                  60483.36
Amica Models & Co.            82223.23
Anna's Decorations, Ltd      137034.22
Atelier graphique             22314.36
...                                ...
Vida Sport, Ltd              108777.92
Vitachrome Inc.               72497.64
Volvo Model Replicas, Co      66694.82
West Coast Collectables Co.   43748.72
giftsbymail.co.uk             71783.75

[98 rows x 1 columns]

In [122]:
total_sale_per_cuutomer.iloc[[0,1,2],[0]]

                        total
                          sum
customerName
AV Stores, Co.      148410.09
Alpha Cognac         60483.36
Amica Models & Co.   82223.23

In [ ]:
total_sale_per_cuutomer.max()

total  sum    820689.54
dtype: float64

In [ ]:
total_sale_per_cuutomer[]